### PR TITLE
Feature Request #85 - Make icons more consistent in style

### PR DESCRIPTION
**Pull request by chriscross12324**
Migrated as many icons as I could to the Material Design Rounded style. Some icons don't exist in the Material Design Library, so I took some creative liberty. Let me know what you think, I'm open to collaboration on this.

### CODE REVIEW

**Comment by chriscross12324** [comment]
I understand some icons are purposefully different to add style (ex. the Navbar icons), let me know how you feel about those.

**Review by starry-shivam — COMMENTED** [review]
As I mentioned in my [original reply](https://github.com/Pool-Of-Tears/GreenStash/issues/85#issuecomment-2028530282), icons at certain places like the navigation drawer and goal card are deliberately chosen from a different icon pack. This decision was made because Material Icons didn't look as great in those locations. I had already tested them before switching to different custom vector drawables. Additionally, you replaced icons used by the goal icon picker with rounded icon pack. However, it seems that the rounded icon pack doesn't contain as many icons as the filled one, resulting in a much smaller set of choices for the user.

**Comment by starry-shivam** [comment]
> I understand some icons are purposefully different to add style (ex. the Navbar icons), let me know how you feel about those.

I'll test the look and feel of the app with your changes later. However, please also take a look at the other point I mentioned in my comment.

**Comment by starry-shivam** [comment]
Closing due to no response

**Pull request closed without merging**
