### PR TITLE
Improvements in the Spanish translation

### PR DESCRIPTION
**Pull request by IngrownMink4**
Hi!

I have improved the syntactic, grammatical and spelling structure of all text strings. There are still some that have room for improvement, but for now it is better than what was posted before, as it is now readable and usable.

If there is any problem with the pull request or you want to ask me something about commits, don't hesitate to contact me <3

Greetings,
@IngrownMink4

### CODE REVIEW

**Comment by starry69** [comment]
Hey! First of all thankyou for taking time to work on these improvements! I'll take a look at them tomorrow, btw if you don't mind can we keep this PR open for sometime? as I've been working on an update to improve the app bit more and maybe add few requested features such i.e #6 and #7 which will add some new strings to the app, which you can translate aswell if there isn't any problem ofcourse. That way the translation will be 100% up to date with English string resources, otherwise it'll lag behind if i merge this right now and start working on the above mentioned stuffs afterwards. I'll let you know when it's done so you could complete the translation. Lemme know if you're comfortable with that.

**Comment by IngrownMink4** [comment]
> Hey! First of all thankyou for taking time to work on these improvements! I'll take a look at them tomorrow, btw if you don't mind can we keep this PR open for sometime? as I've been working on an update to improve the app bit more and maybe add few requested features such i.e #6 and #7 which will add some new strings to the app, which you can translate aswell if there isn't any problem ofcourse. That way the translation will be 100% up to date with English string resources, otherwise it'll lag behind if i merge this right now and start working on the above mentioned stuffs afterwards. I'll let you know when it's done so you could complete the translation. Lemme know if you're comfortable with that.

I think it's a good idea. As you say, the translation would be on par with the original English translation. And yes, I will be happy to help you with any new strings you add. When you add them, mention me and I will try to contribute as soon as possible :)

**Comment by starry69** [comment]
Thanks, will do 👍

**Comment by starry69** [comment]
Hey @IngrownMink4 I've completed those two issues which we talked about earlier, you can get started with your translations by taking reference from new updated english string resource file.

**Comment by IngrownMink4** [comment]
> 



> Hey @IngrownMink4 I've completed those two issues which we talked about earlier, you can get started with your translations by taking reference from new updated english string resource file.

I've already solved the conflict, everything should be ok! Please check it.

**Comment by starry69** [comment]
Looks great! Thanks for your contribution.

**Pull request merged**
